### ISSUE TITLE
Not working nexus 6 android 8.1

### ISSUE THREAD

**Issue by psychoela** [Magisk-Modules-Repo/wifi-bonding#12]
- Copying zip to temp directory
cat: write error: Broken pipe
- Installing Wifi_Bonding_(Qualcomm)-1.9.zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: common/post-fs-data.sh
  inflating: common/service.sh
  inflating: common/system.prop
  inflating: config.sh
  inflating: module.prop
*******************************
      Magisk WiFi Bonding      
*******************************
******************************
Powered by Magisk (@topjohnwu)
******************************
- Creating /data/adb/magisk_merge.img with size 64M
Creating filesystem with parameters:
    Size: 67108864
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4096
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16384
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4096 inodes and 1294/16384 blocks
Create /data/adb/magisk_merge.img with size 64M
e2fsck 1.43.3 (04-Sep-2016)
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
- Extracting module files
- Migrating WCNSS_qcom_cfg.ini
- Migration FAILED. 
  Please report it to the developer with
  your WCNSS_qcom_cfg.ini path.
- Setting permissions
- Done
- All done!

**Comment by simonsmh** [comment]
Nexus 6 didn't have WCNSS_qcom_cfg.ini for their driver. That's expected.
