### ISSUE TITLE
latest version boot loop

### ISSUE THREAD

**Issue by steven7851** [Magisk-Modules-Repo/wifi-bonding#16]
boot log say:
[ 05-11 22:20:03.560  1259: 1260 E/Magisk   ]
mount /sbin/.magisk/img/wifi-bonding/vendor/etc/wifi/WCNSS_qcom_cfg.ini->/vendor/etc/wifi/WCNSS_qcom_cfg.ini failed with 2: No such file or directory

**Comment by simonsmh** [comment]
Where is your ini located?
It seems that `/vendor/etc/wifi/WCNSS_qcom_cfg.ini` doesn't exist

**Comment by steven7851** [comment]
`/vendor/etc/wifi/WCNSS_qcom_cfg.ini` does exist
and `/vendor` is symlink to `/system/vendor`

I try install old zip without new installer, and it boot normally.
