### ISSUE TITLE
Does not install on v18.1

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/wifi-bonding#17]
After download of current version installation process fails on lateste stable Magisk.

**Comment by simonsmh** [comment]
Install from recovery works

**Comment by gjf** [comment]
![Screenshot_2019-03-30-14-23-20-476_com topjohnwu magisk](https://user-images.githubusercontent.com/322186/55275638-ec853d00-52f9-11e9-9a87-4956d4bb4048.png)

**Comment by ghost** [comment]
![Screenshot_20190330-135615](https://user-images.githubusercontent.com/3320229/55275773-bf359080-52f3-11e9-85b9-75f88c82bbc6.jpg)

@simonsmh

**Comment by gjf** [comment]
After update to latest version the system stopped booting.
Disabling the module (in recovery) helps.
Have to switch back to older version.

**Comment by simonsmh** [comment]
Provide logs would be helpful

**Comment by gjf** [comment]
I'd be happy, but which one? As I told the phone stucks at logo with no booting.

**Comment by simonsmh** [comment]
at least it could boot to twrp, take logs from /cache

**Comment by gjf** [comment]
If you wish to ispect magisk.log - it is zero-sized.
The latest version that works for me is attached. All later updates leads to stuck at boot logo.
[Wifi_Bonding_(Qualcomm)-1.9.zip](https://github.com/Magisk-Modules-Repo/wifi-bonding/files/3029384/Wifi_Bonding_.Qualcomm.-1.9.zip)

**Comment by simonsmh** [comment]
Are you using v19 or v18.1? I think that might be an upstream issue.

**Comment by gjf** [comment]
I am using 18.1 as a latest stable/released version.
As far as 19 is beta I don't want to install it until test process will be finished completely by the author.
