### ISSUE TITLE
I can't install version 1.10 with magisk 19.1

### ISSUE THREAD

**Issue by RYU81** [Magisk-Modules-Repo/wifi-bonding#19]
- Copying zip to temp directory
- Installing Wifi_Bonding_(Qcom)-1.10.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: install.sh
  inflating: module.prop
**************************
Magisk Wifi Bonding (Qcom)
**************************
******************************
Powered by Magisk (@topjohnwu)
******************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
   creating: system/
  inflating: system/placeholder
- Extracting module files
- Migration FAILED. Please report it to the developer with your WCNSS_qcom_cfg.ini path.
! Installation failed

**Comment by simonsmh** [comment]
Can you find WCNSS_qcom_cfg.ini in your system?

**Comment by RYU81** [comment]
no

> Can you find WCNSS_qcom_cfg.ini in your system?
No

**Comment by RYU81** [comment]
No
