### ISSUE TITLE
Not persistent

### ISSUE THREAD

**Issue by Shenron0** [Magisk-Modules-Repo/wifi-bonding#21]
Apparently if the wifi that the device is already connected to changes to a different one and then back, the link speed drops back down below 150mbps. Not sure if it is just the phone or the wifi that's the problem. OnePlus 6 OS 9 beta

**Comment by simonsmh** [comment]
That could either be a router problem or a driver problem. If the device has a bad connection status, it might tune itself for a better network link to improve connectivity.
