### ISSUE TITLE
Causes heavy battery drain

### ISSUE THREAD

**Issue by MarcAnt01** [Magisk-Modules-Repo/wifi-bonding#22]
When connected to WiFi, the power consumption is increased a lot

**Comment by MarcAnt01** [comment]
Reason of the closure?

**Comment by simonsmh** [comment]
What do you expect me to fix?
The reason for power consumption varies from device to device, Wi-Fi chipset won't eat more power than your daily apps.

If you major in EE, you could dive deeper. See [Power Consumption and Energy Efficiency of 802.11 Network Devices](https://pdfs.semanticscholar.org/5bb6/74e98252e77ce8bab3ea4ccd99eec06bd3f3.pdf) from IEEE and [Energy consumption anatomy of 802.11 devices and its implication on modeling and design](https://www.it.uc3m.es/banchs/papers/conext12.pdf) from ACM.

**Comment by MarcAnt01** [comment]
I didn't expect anything to be fixed just an answer, since I noticed that the module increases power consumption if enabled. My device is OnePlus 3

**Comment by simonsmh** [comment]
I was also using OnePlus 3 while creating this module, but I didn't notice the power consumption before. Fell free to uninstall the module if it affects you.

**Comment by MarcAnt01** [comment]
Well, I don't understand why blaming me or asking to uninstall if I don't like. I mean in the README you write that issues and pr are welcome and you start to be unkind just if someone reports that...

**Comment by simonsmh** [comment]
I'm not blaming you. I'm not good at English, sorry about that. If you feel my unkind, I apologize.
