### ISSUE TITLE
android10 miui11 not work

### ISSUE THREAD

**Issue by mjyhj** [Magisk-Modules-Repo/wifi-bonding#25]
android10 miui11 WCNSS_qcom_cfg.ini
### # gForce1x1Exception=0

There is a space after # 

So it can't be replaced “#gForce1x1Exception=0”

**Comment by simonsmh** [comment]
Does gForce1x1Exception=0 is set to default?

**Comment by mjyhj** [comment]
install.sh
```
s/gForce1x1Exception=1/gForce1x1Exception=0/g
s/#gForce1x1Exception=0/gForce1x1Exception=0/g
```

android10 miui11 WCNSS_qcom_cfg.ini  (default)
`# gForce1x1Exception=1`


Need to add in WCNSS_qcom_cfg.ini
```
s/#g Force1x1Exception=0/gForce1x1Exception=0/g
s/#g Force1x1Exception=1/gForce1x1Exception=0/g
```
