### ISSUE TITLE
OnePlus 3 on OxygenOS 9.0.5 (Android 9) WCNSS_qcom_cfg.ini

### ISSUE THREAD

**Issue by SubZero5** [Magisk-Modules-Repo/wifi-bonding#26]
Hi,

My OnePlus 3 running OxygenOS 9.0.5 which is an Android 9 running device that has a `WCNSS_qcom_cfg.ini` file located at `/system/vendor/etc/wifi/`.

The file is here: [WCNSS_qcom_cfg.ini](https://www.mediafire.com/file/0864q3el5rnimf4/WCNSS_qcom_cfg.ini/file)

**Comment by simonsmh** [comment]
Have you installed the module? There should be no problem on op3
