### ISSUE TITLE
No effect No change

### ISSUE THREAD

**Issue by ReDsTaR-22** [Magisk-Modules-Repo/wifi-bonding#27]
I have installed the module then followed the steps then flashed it . but still the max link speed is 65 mb nothing changed! any ideas to solve this??

**Comment by simonsmh** [comment]
Check the configuration of the router.

**Comment by ReDsTaR-22** [comment]
what settings do i change in the router configuration?

**Comment by MarkasDaemon** [comment]
First install module then remove connected wifi network then reboot then go to wifi and  connect with network again (removed one) and see properties.. Mi 8 SE android 9 miui 11 working Module
![IMG_20200423_134848](https://user-images.githubusercontent.com/37901153/80078345-99b79c80-8570-11ea-8d02-2e495a08a99e.jpg)

**Comment by ReDsTaR-22** [comment]
Still link speed is 65mbps. Is it working only on android 9 ?? I am using android 5 panasonic eluga mark phone
