### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by Jakesnowy** [Magisk-Modules-Repo/wifi-bonding#3]
Hey there! Just wanted to report in for ph2n, we have the ini file in two locations
/system/etc/wifi
And
/system/etc/firmware/wlan/prima

Thank you for your work :)

**Comment by simonsmh** [comment]
They should be both supported already. Please post magisk logs if you meet any problem when using.

**Comment by woodee23** [comment]
Its also in /data/misc/wifi on ph2n

**Comment by simonsmh** [comment]
But magisk couldn't control the wifi config in data slot.
Please send a copy of ini file in /system/etc/wifi/ to me. Thanks.

**Comment by woodee23** [comment]
oh no know that module works great... I was just simply commenting on the
guy who said that it's only what he said it was I have for the LG Stylo 2
plus also.. only mine has a custom kernel that I composed myself and at the
bloated deodexed ROM made by me usb OTG enabled by me all that anyway
thanks anyway
