### ISSUE TITLE
Lenovo A6000 Plus

### ISSUE THREAD

**Issue by akyrone** [Magisk-Modules-Repo/wifi-bonding#5]
I have this file,WCNSS_qcom_cfg.ini
What do I do now?
[WCNSS_qcom_cfg.ini.txt](https://github.com/Magisk-Modules-Repo/magisk-wifi-bonding/files/1895687/WCNSS_qcom_cfg.ini)

**Comment by simonsmh** [comment]
file location please

**Comment by akyrone** [comment]
i already attach the file before..
the file is locate at: -
/system/etc
![screenshot_20180411-212722](https://user-images.githubusercontent.com/11782075/38619664-42d096b4-3dcf-11e8-9ed9-4d2fa73c64c4.png)
/wifi/

**Comment by simonsmh** [comment]
Already supported.
