### ISSUE TITLE
Support for OnePlus (with Android Oreo)

### ISSUE THREAD

**Issue by axeldna** [Magisk-Modules-Repo/wifi-bonding#6]
Hi,
This module used to work with OnePlus 3 up to OnePlus 5T, however, I think after the Android Oreo update it's not working.

Probably because the location of the WCNSS_qcom_cfg.ini file up to Android Nougat was: **system/etc/wifi**.
Now, in Android Oreo, it's located in **system/vendor/etc/wifi**.

Is there a way fix it without compromising the not updated OnePlus 3 to 5 phones? I will be glad to provide help and feedback.

**Comment by simonsmh** [comment]
Reinstall this module please.

**Comment by axeldna** [comment]
Didn't work. As I can see, the module is still pointing to system/etc/wifi.

**Comment by simonsmh** [comment]
https://github.com/Magisk-Modules-Repo/magisk-wifi-bonding/blob/master/META-INF/com/google/android/update-binary#L161
That has already been supported months ago, and I tested it on my oneplus3 and it's working.
I have no idea what is going on on your device. Please give me your log.

**Comment by axeldna** [comment]
Thank you for your reply. Great to know you have a OnePlus 3 too.

I checked the file and double band is indeed enabled for 2.4Ghz, however, when I see properties for any wifi network using 2.4ghz, link speed is still 72mbps. Maybe the file is being modified after the system has completely booted?

Anyway, how can I provide you a specific log?

**Comment by simonsmh** [comment]
Magisk Manager-logs-save logs
Magisk has tweaked init, which is the way Android boot. I don't think that's the case. Maybe oneplus just write the config into the firmware or driver and refused to read the config outside but I'm not sure. BTW, have you checked that if it works under third party roms like lineage?

**Comment by axeldna** [comment]
[magisk_log_20180514_191051.log](https://github.com/Magisk-Modules-Repo/magisk-wifi-bonding/files/2003040/magisk_log_20180514_191051.log)

I rebooted before saving the log so it can be easier to check. Haven't tried with any other roms, because my last two attempts were not good. 

One more thing that probably helps to address the issue: when I modified the file manually (directly updating the system file) without Magisk it worked, so I guess the config is not in the firmware or driver.

I could get the dual band with that method, but I honestly prefer systemless stuff controlled by Magisk.

**Comment by simonsmh** [comment]
That's weird. Do you think it is a Magisk bug?

**Comment by axeldna** [comment]
Hi, after many attempts to try to find the source of the issue (tried removing/reinstalling Magisk, removing/reinstalling module, removing/reinstalling Xposed, removing/disabling some root apps), I managed to "fix" the problem.

Can't explain why (maybe a bug?), but I had to remove all my saved wifi networks to properly make this module works. Here are the steps I followed:
1. Removed the installed Wifi Bonding module.
2. Removed all saved wifi 2.4Ghz networks (I removed all of them anyway, but shouldn't be necessary).
3. Rebooted the phone (to make sure wifi settings are removed from cloud account too).
4. Installed the Wifi Bonding module.
5. Rebooted the phone (as indicated by Magisk to start the module).
6. With a phone "free of wifi" and with a fresh Wifi Bonding module, I joined 2.4Ghz wifi networks.
7. Checked my newly registered 2.4Ghz networks and they are showing 150Mbps Link Speed.

Would be nice if you can suggest in the module repository a description or comment about what I did to make this module work. What do you think? I guess you can close this issue when you answer. I really hope my experience can help people who may have a similar problem.

**Comment by simonsmh** [comment]
OK, I'll put it in readme.md later.
Thank you!

**Comment by pro4tlzz** [comment]
I have the same issue and it only worked once, after that it went back to 72mbps
