### ISSUE TITLE
Doesn't working on Redmi 5 Plus

### ISSUE THREAD

**Issue by JackCui001** [Magisk-Modules-Repo/wifi-bonding#8]
Maybe MIUI is to blame?
There's the config file in /system.

**Comment by simonsmh** [comment]
Have you tried the instructions at readme.md?
And please give me the full path to the file

**Comment by JackCui001** [comment]
I think I know what the problem is.
I found two ini files in different directories.
One is in /system/etc/wifi/WCNSS_qcom_cfg.ini
The other is in /data/misc/wifi/WCNSS_qcom_cfg.ini
The first one is that you module modify with "gChannelBondingMode24GHz=1".
The second one wasn't modified.
I add that code manually, then it works.
It's so weird.

**Comment by JackCui001** [comment]
刚刚才发现老哥是国人啊= =还是说中文吧

**Comment by JackCui001** [comment]
我觉得模块可能修改了错误的ini文件，导致没有效果，不知道为啥我这手机会有两个文件…

**Comment by simonsmh** [comment]
我还是第一次见放 /data/misc/wifi/WCNSS_qcom_cfg.ini 的，magisk不能替换data的文件，很有可能无解

**Comment by JackCui001** [comment]
奇怪的MIUI😂可以用符号链接吗？

**Comment by JackCui001** [comment]
刚刚又发现一件事，/system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini这也有个文件，但是是符号链接，实际链接到/data/misc/wifi/WCNSS_qcom_cfg.ini

**Comment by simonsmh** [comment]
你data可以直接改的话就直接改吧（
像system和vendor都是readonly的，改起来成本太高，所以上magisk

**Comment by JackCui001** [comment]
改是可以改，但真的没有systemless的方法吗😢

**Comment by simonsmh** [comment]
你改data本来就是systemless啊（（（

**Comment by JackCui001** [comment]
看来我对systemless的理解有问题啊🌚
我以为只要影响到ota就等于破坏systemless了
谢谢啦

**Comment by simonsmh** [comment]
改data不影响ota呀？

**Comment by JackCui001** [comment]
额，那可能是xposed的锅吧
